import { INFTDetail } from "@/types";

export const uNFTData: INFTDetail[] = [
  {
    id: 1,
    name: "Azuki",
    slug: "azuki",
    uasset_contract_address: "0xf8CA97BE31E89D3FfB229F7AB8483bB9bB63F4fB",
    uName: "uAzuki",
    img: "https://uniasset.oss-cn-hongkong.aliyuncs.com/token/azuki.pic.jpg",
    display_name: "Azuki",
    bought: 0,
    count_onsale: 0,
    floor_price: 0,
    history_data_table: "",
    in_hold: 0,
    belong: 0,
    listed_ratio: 0,
    num_owners: 0,
    total_supply: 0,
    total_volume: 0,
    type: "",
    asset_address: "",
    url: "",
    variation_eth: 0,
    "24h_volume": 0,
  },
  {
    id: 2,
    name: "beanz-official",
    slug: "beanz-official",
    uasset_contract_address: "0x3F767247aF189f6dF7660e105CD4a8E5632215f6",
    uName: "uBeanz",
    img: "https://uniasset.oss-cn-hongkong.aliyuncs.com/token/13091656434593_.pic.jpg",
    display_name: "BEANZ",
    bought: 0,
    count_onsale: 0,
    floor_price: 0,
    history_data_table: "",
    in_hold: 0,
    belong: 0,
    listed_ratio: 0,
    num_owners: 0,
    total_supply: 0,
    total_volume: 0,
    type: "",
    asset_address: "",
    url: "",
    variation_eth: 0,
    "24h_volume": 0,
  },
  {
    id: 3,
    name: "doodles",
    slug: "doodles",
    uasset_contract_address: "0x6C67cD5E815F6E274DFf75A4ee180e3cF49f98eD",
    uName: "uDoodles",
    img: "https://uniasset.oss-cn-hongkong.aliyuncs.com/token/13101656434599_.pic.jpg",
    display_name: "Doodles",
    bought: 0,
    count_onsale: 0,
    floor_price: 0,
    history_data_table: "",
    in_hold: 0,
    belong: 0,
    listed_ratio: 0,
    num_owners: 0,
    total_supply: 0,
    total_volume: 0,
    type: "",
    asset_address: "",
    url: "",
    variation_eth: 0,
    "24h_volume": 0,
  },
  {
    id: 4,
    name: "bored-ape-yacht-club",
    slug: "bored-ape-yacht-club",
    uasset_contract_address: "0x61fDa6A13C255497146708A834896D70c33e41fe",
    uName: "uBoredApe",
    img: "https://uniasset.oss-cn-hongkong.aliyuncs.com/token/13111656434603_.pic.jpg",
    display_name: "BoredApe",
    bought: 0,
    count_onsale: 0,
    floor_price: 0,
    history_data_table: "",
    in_hold: 0,
    belong: 0,
    listed_ratio: 0,
    num_owners: 0,
    total_supply: 0,
    total_volume: 0,
    type: "",
    asset_address: "",
    url: "",
    variation_eth: 0,
    "24h_volume": 0,
  },
  {
    id: 5,
    name: "proof-moonbirds",
    slug: "proof-moonbirds",
    uasset_contract_address: "0x91aE457665E95cADBd7630587FdF925afF065694",
    uName: "uMoonBirds",
    img: "https://uniasset.oss-cn-hongkong.aliyuncs.com/token/13121656434613_.pic.jpg",
    display_name: "moonbirds",
    bought: 0,
    count_onsale: 0,
    floor_price: 0,
    history_data_table: "",
    in_hold: 0,
    belong: 0,
    listed_ratio: 0,
    num_owners: 0,
    total_supply: 0,
    total_volume: 0,
    type: "",
    asset_address: "",
    url: "",
    variation_eth: 0,
    "24h_volume": 0,
  },
];